# -*- coding: utf-8 -*-
"""PROJECT-104

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wOs1blzapvvcFf9b6la_llhNwkOMiZj
"""

from google.colab import files 
data_to_load=files.upload()

#MEAN

import csv
with open("SOCR-HeightWeight.csv", newline='') as f:
  reader =csv.reader(f)
  fileData= list(reader)

fileData.pop(0)
new_data= []
for i in range(len(fileData)):
  n_num = fileData[i][1]
  new_data.append(float(n_num))

n=len(new_data)
total=0
for x in new_data:
  total += x
mean = total/n

print('Mean/average is : '+str(mean))

#MEDIAN

if n%2 == 0 :
  median1=float(new_data[n//2])
  median2=float(new_data[n//2-1])
  median=(median1+median2)/2
else:
  median= new_data[n//2]
print('Median/centre is : '+str(median))

#MODE

from collections import Counter
new_data='WhitehatJR'
data=Counter(new_data)
print(data)